#!/usr/bin/env python3
"""Generate typed Lua wrapper stubs for Godot + project classes.

The generated files are intentionally lightweight EmmyLua/LuaLS annotations. They
are safe to commit, easy to diff, and do not replace the C++ Variant bridge; they
provide editor/type information for large Godot projects that use Lua scripts.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

LUA_KEYWORDS = {
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
    "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true",
    "until", "while",
}

TYPE_MAP = {
    "void": "nil",
    "Nil": "nil",
    "bool": "boolean",
    "boolean": "boolean",
    "int": "integer",
    "int32": "integer",
    "int64": "integer",
    "float": "number",
    "double": "number",
    "real_t": "number",
    "String": "string",
    "StringName": "string",
    "NodePath": "string",
    "Variant": "any",
    "Array": "table",
    "Dictionary": "table",
    "PackedStringArray": "string[]",
    "PackedInt32Array": "integer[]",
    "PackedInt64Array": "integer[]",
    "PackedFloat32Array": "number[]",
    "PackedFloat64Array": "number[]",
    "PackedByteArray": "integer[]",
}

CLASS_NAME_RE = re.compile(r"^\s*class_name\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)
EXTENDS_RE = re.compile(r"^\s*extends\s+([A-Za-z_][A-Za-z0-9_./]*)", re.MULTILINE)
LUA_EXTENDS_RE = re.compile(r"^\s*--\s*@extends\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)
LUA_CLASS_RE = re.compile(r"^\s*--\s*@class\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)


def sanitize_ident(name: str, fallback: str = "arg") -> str:
    if not name:
        return fallback
    name = re.sub(r"\W+", "_", name)
    if name[0].isdigit():
        name = f"_{name}"
    if name in LUA_KEYWORDS:
        name = f"{name}_"
    return name


def lua_type(godot_type: Optional[str]) -> str:
    if not godot_type:
        return "any"
    godot_type = godot_type.replace("const ", "").replace("&", "").replace("*", "").strip()
    if godot_type.startswith("typedarray::"):
        inner = godot_type.split("::", 1)[1]
        return f"{lua_type(inner)}[]"
    return TYPE_MAP.get(godot_type, godot_type)


def get_classes(api: Dict[str, Any]) -> List[Dict[str, Any]]:
    return list(api.get("classes", [])) + list(api.get("builtin_classes", []))


def method_args(method: Dict[str, Any]) -> List[Dict[str, str]]:
    args = []
    for i, arg in enumerate(method.get("arguments", []) or []):
        args.append({
            "name": sanitize_ident(arg.get("name", f"arg{i}"), f"arg{i}"),
            "type": lua_type(arg.get("type", "Variant")),
        })
    return args


def render_class_stub(cls: Dict[str, Any]) -> str:
    name = cls.get("name", "Unknown")
    inherits = cls.get("inherits") or cls.get("base_class") or ""
    lines: List[str] = [
        "---@meta",
        "-- Generated by tools/generate_api_wrappers.py. Do not edit manually.",
        "",
    ]
    if inherits:
        lines.append(f"---@class {name}: {inherits}")
    else:
        lines.append(f"---@class {name}")
    lines.append(f"local {name} = {{}}")
    lines.append("")

    for prop in cls.get("properties", []) or []:
        prop_name = sanitize_ident(prop.get("name", "property"), "property")
        prop_type = lua_type(prop.get("type", "Variant"))
        lines.append(f"---@field {prop_name} {prop_type}")
    if cls.get("properties"):
        lines.append("")

    for method in cls.get("methods", []) or []:
        method_name = sanitize_ident(method.get("name", "method"), "method")
        args = method_args(method)
        for arg in args:
            lines.append(f"---@param {arg['name']} {arg['type']}")
        return_type = lua_type(method.get("return_value", {}).get("type") or method.get("return_type") or "void")
        if return_type != "nil":
            lines.append(f"---@return {return_type}")
        signature = ", ".join(arg["name"] for arg in args)
        lines.append(f"function {name}:{method_name}({signature}) end")
        lines.append("")

    for constant in cls.get("constants", []) or []:
        const_name = sanitize_ident(constant.get("name", "CONSTANT"), "CONSTANT")
        value = constant.get("value", 0)
        lines.append(f"{name}.{const_name} = {value}")
    if cls.get("constants"):
        lines.append("")

    lines.append(f"return {name}")
    lines.append("")
    return "\n".join(lines)


def discover_project_classes(project_dir: Path) -> List[Dict[str, str]]:
    classes: List[Dict[str, str]] = []
    if not project_dir.exists():
        return classes

    for path in sorted(project_dir.rglob("*.gd")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        class_match = CLASS_NAME_RE.search(text)
        if not class_match:
            continue
        extends_match = EXTENDS_RE.search(text)
        classes.append({
            "name": class_match.group(1),
            "inherits": extends_match.group(1).replace("/", ".") if extends_match else "Node",
            "path": str(path.relative_to(project_dir)),
            "source": "gdscript",
        })

    for path in sorted(project_dir.rglob("*.lua")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        class_match = LUA_CLASS_RE.search(text)
        if not class_match:
            continue
        extends_match = LUA_EXTENDS_RE.search(text)
        classes.append({
            "name": class_match.group(1),
            "inherits": extends_match.group(1) if extends_match else "Node",
            "path": str(path.relative_to(project_dir)),
            "source": "lua",
        })
    return classes


def render_project_class_stub(cls: Dict[str, str]) -> str:
    return "\n".join([
        "---@meta",
        "-- Generated project class wrapper. Do not edit manually.",
        "",
        f"---@class {cls['name']}: {cls['inherits']}",
        f"---@field __godot_script_path string '{cls['path']}'",
        f"local {cls['name']} = {{}}",
        "",
        f"return {cls['name']}",
        "",
    ])


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate typed Lua stubs for Godot Lua projects.")
    parser.add_argument("--api", type=Path, required=True, help="Path to Godot extension_api.json.")
    parser.add_argument("--project", type=Path, default=None, help="Optional Godot project directory to scan for project classes.")
    parser.add_argument("--out", type=Path, default=Path("generated/lua_api"), help="Output directory for generated Lua modules.")
    parser.add_argument("--limit", type=int, default=0, help="Optional class generation limit for smoke tests.")
    args = parser.parse_args()

    api = json.loads(args.api.read_text(encoding="utf-8"))
    classes = get_classes(api)
    if args.limit > 0:
        classes = classes[: args.limit]

    godot_dir = args.out / "godot" / "classes"
    generated: List[str] = []
    for cls in classes:
        name = cls.get("name")
        if not name:
            continue
        write_file(godot_dir / f"{name}.lua", render_class_stub(cls))
        generated.append(f"godot.classes.{name}")

    project_classes: List[Dict[str, str]] = []
    if args.project is not None:
        project_classes = discover_project_classes(args.project)
        for cls in project_classes:
            write_file(args.out / "godot" / "project" / f"{cls['name']}.lua", render_project_class_stub(cls))
            generated.append(f"godot.project.{cls['name']}")

    init_lines = [
        "---@meta",
        "-- Generated Godot Lua API index. Do not edit manually.",
        "",
        "local godot_api = {}",
    ]
    for module in generated:
        init_lines.append(f"-- require('{module}')")
    init_lines.extend(["", "return godot_api", ""])
    write_file(args.out / "godot" / "init.lua", "\n".join(init_lines))

    manifest = {
        "api": str(args.api),
        "project": str(args.project) if args.project else None,
        "class_count": len(classes),
        "project_class_count": len(project_classes),
        "output": str(args.out),
    }
    write_file(args.out / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
